/**
 * Generates lib/database.types.ts by introspecting the live schema.
 *
 * `supabase gen types --project-id` needs a dashboard access token we do not
 * have in this environment, so we read the catalog over the same pooler
 * connection the migrations use.
 *
 *   node supabase/gen-types.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const here = dirname(fileURLToPath(import.meta.url));

function loadEnv() {
  const env = {};
  try {
    const raw = readFileSync(join(here, "..", ".env"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
      if (m) env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
    }
  } catch {
    /* fall through */
  }
  // .env wins over the ambient shell (see migrate.mjs).
  return { ...process.env, ...env };
}

const env = loadEnv();
const projectRef = (env.NEXT_PUBLIC_SUPABASE_URL || "").match(
  /https:\/\/([a-z0-9]+)\.supabase\.co/,
)?.[1];

const client = new pg.Client({
  host: `aws-0-${env.SUPABASE_REGION || "eu-west-1"}.pooler.supabase.com`,
  port: 5432,
  user: `postgres.${projectRef}`,
  password: env.SUPABASE_DB_PASSWORD,
  database: "postgres",
  ssl: { rejectUnauthorized: false },
  connectionTimeoutMillis: 30000,
});

/** Postgres type -> TypeScript type. */
function tsType(dataType, udtName, enums) {
  if (enums.has(udtName)) return `Database["public"]["Enums"]["${udtName}"]`;
  switch (dataType) {
    case "integer":
    case "bigint":
    case "smallint":
    case "numeric":
    case "real":
    case "double precision":
      return "number";
    case "boolean":
      return "boolean";
    case "jsonb":
    case "json":
      return "Json";
    case "ARRAY":
      return "string[]";
    default:
      return "string"; // text, uuid, timestamptz, enums handled above
  }
}

const pascal = (s) => s.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase());

await client.connect();

/* json_agg rather than array_agg: the pg driver hands back array_agg as a
   Postgres array literal string, but parses json into a real JS array. */
const { rows: enumRows } = await client.query(`
  select t.typname,
         json_agg(e.enumlabel order by e.enumsortorder) as labels
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  where t.typnamespace = 'public'::regnamespace
  group by t.typname order by t.typname
`);
const enumNames = new Set(enumRows.map((r) => r.typname));

const { rows: cols } = await client.query(`
  select c.table_name, c.column_name, c.data_type, c.udt_name,
         c.is_nullable, c.column_default,
         (c.is_identity = 'YES') as is_identity
  from information_schema.columns c
  join information_schema.tables t
    on t.table_name = c.table_name and t.table_schema = c.table_schema
  where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    and c.table_name <> '_migrations'
  order by c.table_name, c.ordinal_position
`);

const tables = {};
for (const c of cols) (tables[c.table_name] ||= []).push(c);

let out = `/**
 * Generated by supabase/gen-types.mjs — do not edit by hand.
 * Regenerate after every migration: \`npm run gen:types\`
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
`;

for (const [table, columns] of Object.entries(tables)) {
  out += `      ${table}: {\n        Row: {\n`;
  for (const c of columns) {
    const t = tsType(c.data_type, c.udt_name, enumNames);
    out += `          ${c.column_name}: ${t}${c.is_nullable === "YES" ? " | null" : ""};\n`;
  }
  out += `        };\n        Insert: {\n`;
  for (const c of columns) {
    const t = tsType(c.data_type, c.udt_name, enumNames);
    // Optional when nullable, defaulted, or identity.
    const optional =
      c.is_nullable === "YES" || c.column_default !== null || c.is_identity;
    out += `          ${c.column_name}${optional ? "?" : ""}: ${t}${c.is_nullable === "YES" ? " | null" : ""};\n`;
  }
  out += `        };\n        Update: {\n`;
  for (const c of columns) {
    const t = tsType(c.data_type, c.udt_name, enumNames);
    out += `          ${c.column_name}?: ${t}${c.is_nullable === "YES" ? " | null" : ""};\n`;
  }
  /* supabase-js requires Relationships on every table. Without it the client's
     conditional types fail to match and every row resolves to `never`. */
  out += `        };\n        Relationships: [];\n      };\n`;
}

out += `    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
    Enums: {
`;
for (const e of enumRows) {
  out += `      ${e.typname}: ${e.labels.map((l) => `"${l}"`).join(" | ")};\n`;
}
out += `    };
  };
};

/** Convenience row aliases. */
`;
for (const table of Object.keys(tables)) {
  out += `export type ${pascal(table)}Row = Database["public"]["Tables"]["${table}"]["Row"];\n`;
}
for (const e of enumRows) {
  out += `export type ${pascal(e.typname)} = Database["public"]["Enums"]["${e.typname}"];\n`;
}

writeFileSync(join(here, "..", "lib", "database.types.ts"), out);
console.log(
  `Wrote lib/database.types.ts — ${Object.keys(tables).length} tables, ${enumRows.length} enums.`,
);

await client.end();
