/**
 * Generated by supabase/gen-types.mjs — do not edit by hand.
 * Regenerate after every migration: `npm run gen:types`
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      applications: {
        Row: {
          id: string;
          programme: string;
          full_name: string;
          email: string;
          institution: string | null;
          country: string | null;
          motivation: string | null;
          status: Database["public"]["Enums"]["application_status"];
          internal_notes: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          programme: string;
          full_name: string;
          email: string;
          institution?: string | null;
          country?: string | null;
          motivation?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          internal_notes?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          programme?: string;
          full_name?: string;
          email?: string;
          institution?: string | null;
          country?: string | null;
          motivation?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          internal_notes?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          subject: string | null;
          message: string;
          type: Database["public"]["Enums"]["contact_type"];
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          subject?: string | null;
          message: string;
          type?: Database["public"]["Enums"]["contact_type"];
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          subject?: string | null;
          message?: string;
          type?: Database["public"]["Enums"]["contact_type"];
          created_at?: string;
        };
      };
      donations: {
        Row: {
          id: string;
          amount_kobo: number;
          currency: Database["public"]["Enums"]["currency_code"];
          donor_name: string | null;
          email: string;
          message: string | null;
          paystack_reference: string;
          payment_status: Database["public"]["Enums"]["payment_status"];
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          amount_kobo: number;
          currency?: Database["public"]["Enums"]["currency_code"];
          donor_name?: string | null;
          email: string;
          message?: string | null;
          paystack_reference: string;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          amount_kobo?: number;
          currency?: Database["public"]["Enums"]["currency_code"];
          donor_name?: string | null;
          email?: string;
          message?: string | null;
          paystack_reference?: string;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paid_at?: string | null;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description_rich: Json | null;
          type: Database["public"]["Enums"]["event_type"];
          starts_at: string;
          ends_at: string | null;
          location_type: Database["public"]["Enums"]["location_type"];
          location_or_link: string | null;
          registration_opens: string | null;
          registration_closes: string | null;
          capacity: number | null;
          banner_url: string | null;
          recording_url: string | null;
          status: Database["public"]["Enums"]["content_status"];
          price_kobo: number | null;
          currency: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description_rich?: Json | null;
          type: Database["public"]["Enums"]["event_type"];
          starts_at: string;
          ends_at?: string | null;
          location_type: Database["public"]["Enums"]["location_type"];
          location_or_link?: string | null;
          registration_opens?: string | null;
          registration_closes?: string | null;
          capacity?: number | null;
          banner_url?: string | null;
          recording_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          price_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description_rich?: Json | null;
          type?: Database["public"]["Enums"]["event_type"];
          starts_at?: string;
          ends_at?: string | null;
          location_type?: Database["public"]["Enums"]["location_type"];
          location_or_link?: string | null;
          registration_opens?: string | null;
          registration_closes?: string | null;
          capacity?: number | null;
          banner_url?: string | null;
          recording_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          price_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      homepage: {
        Row: {
          id: boolean;
          hero_eyebrow: string | null;
          hero_heading: string | null;
          hero_subheading: string | null;
          hero_image_url: string | null;
          about_paragraph: string | null;
          explainer_heading: string | null;
          explainer_body: string | null;
          cta_heading: string | null;
          cta_button_label: string | null;
          cta_button_href: string | null;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          hero_eyebrow?: string | null;
          hero_heading?: string | null;
          hero_subheading?: string | null;
          hero_image_url?: string | null;
          about_paragraph?: string | null;
          explainer_heading?: string | null;
          explainer_body?: string | null;
          cta_heading?: string | null;
          cta_button_label?: string | null;
          cta_button_href?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          hero_eyebrow?: string | null;
          hero_heading?: string | null;
          hero_subheading?: string | null;
          hero_image_url?: string | null;
          about_paragraph?: string | null;
          explainer_heading?: string | null;
          explainer_body?: string | null;
          cta_heading?: string | null;
          cta_button_label?: string | null;
          cta_button_href?: string | null;
          updated_at?: string;
        };
      };
      impact_stats: {
        Row: {
          id: string;
          label: string;
          value: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          value: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          value?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      media: {
        Row: {
          id: string;
          storage_path: string;
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          width: number | null;
          height: number | null;
          alt_text: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          storage_path: string;
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          storage_path?: string;
          file_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text?: string;
          created_at?: string;
        };
      };
      news: {
        Row: {
          id: string;
          title: string;
          slug: string;
          body_rich: Json | null;
          excerpt: string | null;
          featured_image_url: string | null;
          author: string | null;
          published_at: string | null;
          status: Database["public"]["Enums"]["content_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          body_rich?: Json | null;
          excerpt?: string | null;
          featured_image_url?: string | null;
          author?: string | null;
          published_at?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          body_rich?: Json | null;
          excerpt?: string | null;
          featured_image_url?: string | null;
          author?: string | null;
          published_at?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
      };
      newsletter_signups: {
        Row: {
          id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
        };
      };
      pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          body_rich: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          body_rich?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          body_rich?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      partners: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          url: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      paystack_events: {
        Row: {
          id: string;
          event_type: string;
          reference: string | null;
          payload: Json;
          processed_at: string;
        };
        Insert: {
          id: string;
          event_type: string;
          reference?: string | null;
          payload: Json;
          processed_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          reference?: string | null;
          payload?: Json;
          processed_at?: string;
        };
      };
      reach_countries: {
        Row: {
          id: string;
          country_code: string;
          country_name: string;
          note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          country_code: string;
          country_name: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          country_code?: string;
          country_name?: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      registrations: {
        Row: {
          id: string;
          event_id: string;
          full_name: string;
          email: string;
          institution: string | null;
          country: string | null;
          payment_status: Database["public"]["Enums"]["payment_status"];
          paystack_reference: string | null;
          amount_kobo: number | null;
          currency: Database["public"]["Enums"]["currency_code"] | null;
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          full_name: string;
          email: string;
          institution?: string | null;
          country?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paystack_reference?: string | null;
          amount_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"] | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          full_name?: string;
          email?: string;
          institution?: string | null;
          country?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paystack_reference?: string | null;
          amount_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"] | null;
          paid_at?: string | null;
          created_at?: string;
        };
      };
      resources: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          category: Database["public"]["Enums"]["resource_category"];
          body_rich: Json | null;
          file_url: string | null;
          external_url: string | null;
          thumbnail_url: string | null;
          status: Database["public"]["Enums"]["content_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          category: Database["public"]["Enums"]["resource_category"];
          body_rich?: Json | null;
          file_url?: string | null;
          external_url?: string | null;
          thumbnail_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          category?: Database["public"]["Enums"]["resource_category"];
          body_rich?: Json | null;
          file_url?: string | null;
          external_url?: string | null;
          thumbnail_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          name: string;
          role: string | null;
          photo_url: string | null;
          bio: string | null;
          affiliation: string | null;
          linkedin_url: string | null;
          orcid_url: string | null;
          group: Database["public"]["Enums"]["team_group"];
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          affiliation?: string | null;
          linkedin_url?: string | null;
          orcid_url?: string | null;
          group: Database["public"]["Enums"]["team_group"];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          affiliation?: string | null;
          linkedin_url?: string | null;
          orcid_url?: string | null;
          group?: Database["public"]["Enums"]["team_group"];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      testimonials: {
        Row: {
          id: string;
          name: string;
          role: string | null;
          photo_url: string | null;
          quote: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string | null;
          photo_url?: string | null;
          quote: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string | null;
          photo_url?: string | null;
          quote?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      application_status:
        "received" | "under_review" | "accepted" | "waitlisted" | "rejected";
      contact_type: "general" | "partnership";
      content_status: "draft" | "published";
      currency_code: "NGN" | "USD";
      event_type: "webinar" | "course" | "mentorship" | "workshop";
      location_type: "online" | "in_person";
      payment_status:
        "not_required" | "pending" | "paid" | "failed" | "expired" | "refunded";
      resource_category:
        "guide" | "template" | "webinar" | "tool" | "publication";
      team_group: "executive" | "scientific" | "country_lead" | "mentor";
    };
  };
};

/** Convenience row aliases. */
export type ApplicationsRow =
  Database["public"]["Tables"]["applications"]["Row"];
export type ContactMessagesRow =
  Database["public"]["Tables"]["contact_messages"]["Row"];
export type DonationsRow = Database["public"]["Tables"]["donations"]["Row"];
export type EventsRow = Database["public"]["Tables"]["events"]["Row"];
export type HomepageRow = Database["public"]["Tables"]["homepage"]["Row"];
export type ImpactStatsRow =
  Database["public"]["Tables"]["impact_stats"]["Row"];
export type MediaRow = Database["public"]["Tables"]["media"]["Row"];
export type NewsRow = Database["public"]["Tables"]["news"]["Row"];
export type NewsletterSignupsRow =
  Database["public"]["Tables"]["newsletter_signups"]["Row"];
export type PagesRow = Database["public"]["Tables"]["pages"]["Row"];
export type PartnersRow = Database["public"]["Tables"]["partners"]["Row"];
export type PaystackEventsRow =
  Database["public"]["Tables"]["paystack_events"]["Row"];
export type ReachCountriesRow =
  Database["public"]["Tables"]["reach_countries"]["Row"];
export type RegistrationsRow =
  Database["public"]["Tables"]["registrations"]["Row"];
export type ResourcesRow = Database["public"]["Tables"]["resources"]["Row"];
export type TeamMembersRow =
  Database["public"]["Tables"]["team_members"]["Row"];
export type TestimonialsRow =
  Database["public"]["Tables"]["testimonials"]["Row"];
export type ApplicationStatus =
  Database["public"]["Enums"]["application_status"];
export type ContactType = Database["public"]["Enums"]["contact_type"];
export type ContentStatus = Database["public"]["Enums"]["content_status"];
export type CurrencyCode = Database["public"]["Enums"]["currency_code"];
export type EventType = Database["public"]["Enums"]["event_type"];
export type LocationType = Database["public"]["Enums"]["location_type"];
export type PaymentStatus = Database["public"]["Enums"]["payment_status"];
export type ResourceCategory = Database["public"]["Enums"]["resource_category"];
export type TeamGroup = Database["public"]["Enums"]["team_group"];
