/**
 * Generated by supabase/gen-types.mjs — do not edit by hand.
 * Regenerate after every migration: `npm run gen:types`
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      admin_audit: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_email: string;
          action: string;
          resource: string;
          resource_id: string | null;
          summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_email: string;
          action: string;
          resource: string;
          resource_id?: string | null;
          summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          actor_email?: string;
          action?: string;
          resource?: string;
          resource_id?: string | null;
          summary?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      applications: {
        Row: {
          id: string;
          programme: string;
          full_name: string;
          email: string;
          institution: string | null;
          country: string | null;
          motivation: string | null;
          status: Database["public"]["Enums"]["application_status"];
          internal_notes: Json;
          created_at: string;
          updated_at: string;
          programme_id: string | null;
        };
        Insert: {
          id?: string;
          programme: string;
          full_name: string;
          email: string;
          institution?: string | null;
          country?: string | null;
          motivation?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          internal_notes?: Json;
          created_at?: string;
          updated_at?: string;
          programme_id?: string | null;
        };
        Update: {
          id?: string;
          programme?: string;
          full_name?: string;
          email?: string;
          institution?: string | null;
          country?: string | null;
          motivation?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          internal_notes?: Json;
          created_at?: string;
          updated_at?: string;
          programme_id?: string | null;
        };
        Relationships: [];
      };
      assessments: {
        Row: {
          id: string;
          module_id: string;
          kind: Database["public"]["Enums"]["assessment_kind"];
          title: string;
          instructions_rich: Json | null;
          pass_mark: number;
          max_attempts: number | null;
          due_at: string | null;
          submission_type: string;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          module_id: string;
          kind: Database["public"]["Enums"]["assessment_kind"];
          title: string;
          instructions_rich?: Json | null;
          pass_mark?: number;
          max_attempts?: number | null;
          due_at?: string | null;
          submission_type?: string;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          module_id?: string;
          kind?: Database["public"]["Enums"]["assessment_kind"];
          title?: string;
          instructions_rich?: Json | null;
          pass_mark?: number;
          max_attempts?: number | null;
          due_at?: string | null;
          submission_type?: string;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      certificates: {
        Row: {
          id: string;
          enrolment_id: string;
          code: string;
          learner_name: string;
          course_title: string;
          cohort_label: string;
          cohort_dates: string | null;
          completed_on: string;
          revoked_at: string | null;
          revoked_reason: string | null;
          revoked_by: string | null;
          issued_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          enrolment_id: string;
          code: string;
          learner_name: string;
          course_title: string;
          cohort_label: string;
          cohort_dates?: string | null;
          completed_on: string;
          revoked_at?: string | null;
          revoked_reason?: string | null;
          revoked_by?: string | null;
          issued_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          enrolment_id?: string;
          code?: string;
          learner_name?: string;
          course_title?: string;
          cohort_label?: string;
          cohort_dates?: string | null;
          completed_on?: string;
          revoked_at?: string | null;
          revoked_reason?: string | null;
          revoked_by?: string | null;
          issued_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cohort_announcements: {
        Row: {
          id: string;
          cohort_id: string;
          title: string;
          body_rich: Json | null;
          published_at: string | null;
          author_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          title: string;
          body_rich?: Json | null;
          published_at?: string | null;
          author_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          title?: string;
          body_rich?: Json | null;
          published_at?: string | null;
          author_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cohort_waitlist: {
        Row: {
          id: string;
          cohort_id: string;
          learner_id: string;
          created_at: string;
          offered_at: string | null;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          learner_id: string;
          created_at?: string;
          offered_at?: string | null;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          learner_id?: string;
          created_at?: string;
          offered_at?: string | null;
          resolved_at?: string | null;
        };
        Relationships: [];
      };
      cohorts: {
        Row: {
          id: string;
          course_id: string;
          label: string;
          slug: string;
          starts_on: string | null;
          ends_on: string | null;
          enrolment_opens: string | null;
          enrolment_closes: string | null;
          enrolment_closed_manually: boolean;
          capacity: number | null;
          price_kobo: number;
          currency: string;
          pacing: string;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          label: string;
          slug: string;
          starts_on?: string | null;
          ends_on?: string | null;
          enrolment_opens?: string | null;
          enrolment_closes?: string | null;
          enrolment_closed_manually?: boolean;
          capacity?: number | null;
          price_kobo?: number;
          currency?: string;
          pacing?: string;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          label?: string;
          slug?: string;
          starts_on?: string | null;
          ends_on?: string | null;
          enrolment_opens?: string | null;
          enrolment_closes?: string | null;
          enrolment_closed_manually?: boolean;
          capacity?: number | null;
          price_kobo?: number;
          currency?: string;
          pacing?: string;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          subject: string | null;
          message: string;
          type: Database["public"]["Enums"]["contact_type"];
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          subject?: string | null;
          message: string;
          type?: Database["public"]["Enums"]["contact_type"];
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          subject?: string | null;
          message?: string;
          type?: Database["public"]["Enums"]["contact_type"];
          created_at?: string;
        };
        Relationships: [];
      };
      courses: {
        Row: {
          id: string;
          programme_id: string | null;
          slug: string;
          title: string;
          summary: string | null;
          body_rich: Json | null;
          level: string;
          delivery: string;
          duration_label: string | null;
          learning_outcomes: Json;
          prerequisites: Json;
          featured_image_url: string | null;
          sort_order: number;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          programme_id?: string | null;
          slug: string;
          title: string;
          summary?: string | null;
          body_rich?: Json | null;
          level?: string;
          delivery?: string;
          duration_label?: string | null;
          learning_outcomes?: Json;
          prerequisites?: Json;
          featured_image_url?: string | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          programme_id?: string | null;
          slug?: string;
          title?: string;
          summary?: string | null;
          body_rich?: Json | null;
          level?: string;
          delivery?: string;
          duration_label?: string | null;
          learning_outcomes?: Json;
          prerequisites?: Json;
          featured_image_url?: string | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      donations: {
        Row: {
          id: string;
          amount_kobo: number;
          currency: Database["public"]["Enums"]["currency_code"];
          donor_name: string | null;
          email: string;
          message: string | null;
          paystack_reference: string;
          payment_status: Database["public"]["Enums"]["payment_status"];
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          amount_kobo: number;
          currency?: Database["public"]["Enums"]["currency_code"];
          donor_name?: string | null;
          email: string;
          message?: string | null;
          paystack_reference: string;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          amount_kobo?: number;
          currency?: Database["public"]["Enums"]["currency_code"];
          donor_name?: string | null;
          email?: string;
          message?: string | null;
          paystack_reference?: string;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paid_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      enrolments: {
        Row: {
          id: string;
          learner_id: string;
          cohort_id: string;
          state: Database["public"]["Enums"]["enrolment_state"];
          enrolled_at: string;
          completed_at: string | null;
          withdrawn_at: string | null;
          created_at: string;
          updated_at: string;
          payment_status: Database["public"]["Enums"]["enrolment_payment_status"];
          amount_kobo: number;
          currency: string;
          paystack_reference: string | null;
          paid_at: string | null;
          cancelled_at: string | null;
          refunded_at: string | null;
          learner_name_at_enrolment: string | null;
          learner_email_at_enrolment: string | null;
        };
        Insert: {
          id?: string;
          learner_id: string;
          cohort_id: string;
          state?: Database["public"]["Enums"]["enrolment_state"];
          enrolled_at?: string;
          completed_at?: string | null;
          withdrawn_at?: string | null;
          created_at?: string;
          updated_at?: string;
          payment_status?: Database["public"]["Enums"]["enrolment_payment_status"];
          amount_kobo?: number;
          currency?: string;
          paystack_reference?: string | null;
          paid_at?: string | null;
          cancelled_at?: string | null;
          refunded_at?: string | null;
          learner_name_at_enrolment?: string | null;
          learner_email_at_enrolment?: string | null;
        };
        Update: {
          id?: string;
          learner_id?: string;
          cohort_id?: string;
          state?: Database["public"]["Enums"]["enrolment_state"];
          enrolled_at?: string;
          completed_at?: string | null;
          withdrawn_at?: string | null;
          created_at?: string;
          updated_at?: string;
          payment_status?: Database["public"]["Enums"]["enrolment_payment_status"];
          amount_kobo?: number;
          currency?: string;
          paystack_reference?: string | null;
          paid_at?: string | null;
          cancelled_at?: string | null;
          refunded_at?: string | null;
          learner_name_at_enrolment?: string | null;
          learner_email_at_enrolment?: string | null;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description_rich: Json | null;
          type: Database["public"]["Enums"]["event_type"];
          starts_at: string;
          ends_at: string | null;
          location_type: Database["public"]["Enums"]["location_type"];
          location_or_link: string | null;
          registration_opens: string | null;
          registration_closes: string | null;
          capacity: number | null;
          banner_url: string | null;
          recording_url: string | null;
          status: Database["public"]["Enums"]["content_status"];
          price_kobo: number | null;
          currency: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually: boolean;
          created_at: string;
          updated_at: string;
          programme_id: string | null;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description_rich?: Json | null;
          type: Database["public"]["Enums"]["event_type"];
          starts_at: string;
          ends_at?: string | null;
          location_type: Database["public"]["Enums"]["location_type"];
          location_or_link?: string | null;
          registration_opens?: string | null;
          registration_closes?: string | null;
          capacity?: number | null;
          banner_url?: string | null;
          recording_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          price_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually?: boolean;
          created_at?: string;
          updated_at?: string;
          programme_id?: string | null;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description_rich?: Json | null;
          type?: Database["public"]["Enums"]["event_type"];
          starts_at?: string;
          ends_at?: string | null;
          location_type?: Database["public"]["Enums"]["location_type"];
          location_or_link?: string | null;
          registration_opens?: string | null;
          registration_closes?: string | null;
          capacity?: number | null;
          banner_url?: string | null;
          recording_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          price_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"];
          registration_closed_manually?: boolean;
          created_at?: string;
          updated_at?: string;
          programme_id?: string | null;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      homepage: {
        Row: {
          id: boolean;
          hero_eyebrow: string | null;
          hero_heading: string | null;
          hero_subheading: string | null;
          hero_image_url: string | null;
          about_paragraph: string | null;
          explainer_heading: string | null;
          explainer_body: string | null;
          cta_heading: string | null;
          cta_button_label: string | null;
          cta_button_href: string | null;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          hero_eyebrow?: string | null;
          hero_heading?: string | null;
          hero_subheading?: string | null;
          hero_image_url?: string | null;
          about_paragraph?: string | null;
          explainer_heading?: string | null;
          explainer_body?: string | null;
          cta_heading?: string | null;
          cta_button_label?: string | null;
          cta_button_href?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          hero_eyebrow?: string | null;
          hero_heading?: string | null;
          hero_subheading?: string | null;
          hero_image_url?: string | null;
          about_paragraph?: string | null;
          explainer_heading?: string | null;
          explainer_body?: string | null;
          cta_heading?: string | null;
          cta_button_label?: string | null;
          cta_button_href?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      impact_stats: {
        Row: {
          id: string;
          label: string;
          value: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          value: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          value?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      learners: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          country: string | null;
          institution: string | null;
          orcid: string | null;
          verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          country?: string | null;
          institution?: string | null;
          orcid?: string | null;
          verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          country?: string | null;
          institution?: string | null;
          orcid?: string | null;
          verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lesson_materials: {
        Row: {
          id: string;
          lesson_id: string;
          storage_path: string;
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          title: string;
          sort_order: number;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          storage_path: string;
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          title: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          storage_path?: string;
          file_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          title?: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lesson_progress: {
        Row: {
          id: string;
          enrolment_id: string;
          lesson_id: string;
          completed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          enrolment_id: string;
          lesson_id: string;
          completed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          enrolment_id?: string;
          lesson_id?: string;
          completed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      lessons: {
        Row: {
          id: string;
          module_id: string;
          title: string;
          summary: string | null;
          body_rich: Json | null;
          video_embed: Json | null;
          estimated_minutes: number | null;
          sort_order: number;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          module_id: string;
          title: string;
          summary?: string | null;
          body_rich?: Json | null;
          video_embed?: Json | null;
          estimated_minutes?: number | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          module_id?: string;
          title?: string;
          summary?: string | null;
          body_rich?: Json | null;
          video_embed?: Json | null;
          estimated_minutes?: number | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      live_sessions: {
        Row: {
          id: string;
          cohort_id: string;
          title: string;
          starts_at: string;
          duration_minutes: number;
          join_url: string | null;
          recording_embed: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          title: string;
          starts_at: string;
          duration_minutes?: number;
          join_url?: string | null;
          recording_embed?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          title?: string;
          starts_at?: string;
          duration_minutes?: number;
          join_url?: string | null;
          recording_embed?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      media: {
        Row: {
          id: string;
          storage_path: string;
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          width: number | null;
          height: number | null;
          alt_text: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          storage_path: string;
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          storage_path?: string;
          file_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      modules: {
        Row: {
          id: string;
          course_id: string | null;
          cohort_id: string | null;
          title: string;
          summary: string | null;
          sort_order: number;
          release_rule: string;
          release_on: string | null;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id?: string | null;
          cohort_id?: string | null;
          title: string;
          summary?: string | null;
          sort_order?: number;
          release_rule?: string;
          release_on?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string | null;
          cohort_id?: string | null;
          title?: string;
          summary?: string | null;
          sort_order?: number;
          release_rule?: string;
          release_on?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      news: {
        Row: {
          id: string;
          title: string;
          slug: string;
          body_rich: Json | null;
          excerpt: string | null;
          featured_image_url: string | null;
          author: string | null;
          published_at: string | null;
          status: Database["public"]["Enums"]["content_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          body_rich?: Json | null;
          excerpt?: string | null;
          featured_image_url?: string | null;
          author?: string | null;
          published_at?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          body_rich?: Json | null;
          excerpt?: string | null;
          featured_image_url?: string | null;
          author?: string | null;
          published_at?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      newsletter_signups: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          unsubscribe_token: string;
          unsubscribed_at: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          unsubscribe_token?: string;
          unsubscribed_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          unsubscribe_token?: string;
          unsubscribed_at?: string | null;
        };
        Relationships: [];
      };
      pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          body_rich: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          body_rich?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          body_rich?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      partners: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          url: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      paystack_events: {
        Row: {
          id: string;
          event_type: string;
          reference: string | null;
          payload: Json;
          processed_at: string;
        };
        Insert: {
          id: string;
          event_type: string;
          reference?: string | null;
          payload: Json;
          processed_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          reference?: string | null;
          payload?: Json;
          processed_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          role: string;
          full_name: string | null;
          created_at: string;
          email: string | null;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: string;
          full_name?: string | null;
          created_at?: string;
          email?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          full_name?: string | null;
          created_at?: string;
          email?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      programmes: {
        Row: {
          id: string;
          slug: string;
          title: string;
          tagline: string | null;
          audience: string | null;
          format: string | null;
          duration: string | null;
          intro: string | null;
          covers: Json;
          for_who: Json;
          cta_kind: string;
          cta_label: string | null;
          icon_name: string;
          feature_image_url: string | null;
          body_rich: Json | null;
          sort_order: number;
          status: Database["public"]["Enums"]["content_status"];
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          tagline?: string | null;
          audience?: string | null;
          format?: string | null;
          duration?: string | null;
          intro?: string | null;
          covers?: Json;
          for_who?: Json;
          cta_kind?: string;
          cta_label?: string | null;
          icon_name?: string;
          feature_image_url?: string | null;
          body_rich?: Json | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          tagline?: string | null;
          audience?: string | null;
          format?: string | null;
          duration?: string | null;
          intro?: string | null;
          covers?: Json;
          for_who?: Json;
          cta_kind?: string;
          cta_label?: string | null;
          icon_name?: string;
          feature_image_url?: string | null;
          body_rich?: Json | null;
          sort_order?: number;
          status?: Database["public"]["Enums"]["content_status"];
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      quiz_options: {
        Row: {
          id: string;
          question_id: string;
          label: string;
          is_correct: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          question_id: string;
          label: string;
          is_correct?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          question_id?: string;
          label?: string;
          is_correct?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      quiz_questions: {
        Row: {
          id: string;
          assessment_id: string;
          prompt: string;
          explanation: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assessment_id: string;
          prompt: string;
          explanation?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assessment_id?: string;
          prompt?: string;
          explanation?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          form: string;
          ip: string;
          window_start: string;
          count: number;
        };
        Insert: {
          form: string;
          ip: string;
          window_start: string;
          count?: number;
        };
        Update: {
          form?: string;
          ip?: string;
          window_start?: string;
          count?: number;
        };
        Relationships: [];
      };
      reach_countries: {
        Row: {
          id: string;
          country_code: string;
          country_name: string;
          note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          country_code: string;
          country_name: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          country_code?: string;
          country_name?: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      registrations: {
        Row: {
          id: string;
          event_id: string;
          full_name: string;
          email: string;
          institution: string | null;
          country: string | null;
          payment_status: Database["public"]["Enums"]["payment_status"];
          paystack_reference: string | null;
          amount_kobo: number | null;
          currency: Database["public"]["Enums"]["currency_code"] | null;
          paid_at: string | null;
          created_at: string;
          attended_at: string | null;
          cancelled_at: string | null;
          reminder_sent_at: string | null;
          learner_id: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          full_name: string;
          email: string;
          institution?: string | null;
          country?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paystack_reference?: string | null;
          amount_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"] | null;
          paid_at?: string | null;
          created_at?: string;
          attended_at?: string | null;
          cancelled_at?: string | null;
          reminder_sent_at?: string | null;
          learner_id?: string | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          full_name?: string;
          email?: string;
          institution?: string | null;
          country?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          paystack_reference?: string | null;
          amount_kobo?: number | null;
          currency?: Database["public"]["Enums"]["currency_code"] | null;
          paid_at?: string | null;
          created_at?: string;
          attended_at?: string | null;
          cancelled_at?: string | null;
          reminder_sent_at?: string | null;
          learner_id?: string | null;
        };
        Relationships: [];
      };
      resources: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          category: Database["public"]["Enums"]["resource_category"];
          body_rich: Json | null;
          file_url: string | null;
          external_url: string | null;
          thumbnail_url: string | null;
          status: Database["public"]["Enums"]["content_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          category: Database["public"]["Enums"]["resource_category"];
          body_rich?: Json | null;
          file_url?: string | null;
          external_url?: string | null;
          thumbnail_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          category?: Database["public"]["Enums"]["resource_category"];
          body_rich?: Json | null;
          file_url?: string | null;
          external_url?: string | null;
          thumbnail_url?: string | null;
          status?: Database["public"]["Enums"]["content_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      session_attendance: {
        Row: {
          id: string;
          session_id: string;
          enrolment_id: string;
          attended_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          enrolment_id: string;
          attended_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          enrolment_id?: string;
          attended_at?: string;
        };
        Relationships: [];
      };
      submissions: {
        Row: {
          id: string;
          assessment_id: string;
          enrolment_id: string;
          attempt: number;
          state: Database["public"]["Enums"]["submission_state"];
          body_text: string | null;
          storage_path: string | null;
          file_name: string | null;
          answers: Json | null;
          score: number | null;
          passed: boolean | null;
          feedback: string | null;
          marked_by: string | null;
          marked_at: string | null;
          is_late: boolean;
          submitted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assessment_id: string;
          enrolment_id: string;
          attempt?: number;
          state?: Database["public"]["Enums"]["submission_state"];
          body_text?: string | null;
          storage_path?: string | null;
          file_name?: string | null;
          answers?: Json | null;
          score?: number | null;
          passed?: boolean | null;
          feedback?: string | null;
          marked_by?: string | null;
          marked_at?: string | null;
          is_late?: boolean;
          submitted_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assessment_id?: string;
          enrolment_id?: string;
          attempt?: number;
          state?: Database["public"]["Enums"]["submission_state"];
          body_text?: string | null;
          storage_path?: string | null;
          file_name?: string | null;
          answers?: Json | null;
          score?: number | null;
          passed?: boolean | null;
          feedback?: string | null;
          marked_by?: string | null;
          marked_at?: string | null;
          is_late?: boolean;
          submitted_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          name: string;
          role: string | null;
          photo_url: string | null;
          bio: string | null;
          affiliation: string | null;
          linkedin_url: string | null;
          orcid_url: string | null;
          group: Database["public"]["Enums"]["team_group"];
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          affiliation?: string | null;
          linkedin_url?: string | null;
          orcid_url?: string | null;
          group: Database["public"]["Enums"]["team_group"];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          affiliation?: string | null;
          linkedin_url?: string | null;
          orcid_url?: string | null;
          group?: Database["public"]["Enums"]["team_group"];
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      testimonials: {
        Row: {
          id: string;
          name: string;
          role: string | null;
          photo_url: string | null;
          quote: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string | null;
          photo_url?: string | null;
          quote: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string | null;
          photo_url?: string | null;
          quote?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
    Enums: {
      application_status: "received" | "under_review" | "accepted" | "waitlisted" | "rejected";
      assessment_kind: "quiz" | "assignment";
      contact_type: "general" | "partnership";
      content_status: "draft" | "published";
      currency_code: "NGN" | "USD";
      enrolment_payment_status: "not_required" | "pending" | "paid" | "refunded" | "failed";
      enrolment_state: "pending" | "active" | "completed" | "withdrawn";
      event_type: "webinar" | "course" | "mentorship" | "workshop";
      location_type: "online" | "in_person";
      payment_status: "not_required" | "pending" | "paid" | "failed" | "expired" | "refunded";
      resource_category: "guide" | "template" | "webinar" | "tool" | "publication";
      submission_state: "submitted" | "marked" | "returned";
      team_group: "executive" | "scientific" | "country_lead" | "mentor";
    };
  };
};

/** Convenience row aliases. */
export type AdminAuditRow = Database["public"]["Tables"]["admin_audit"]["Row"];
export type ApplicationsRow = Database["public"]["Tables"]["applications"]["Row"];
export type AssessmentsRow = Database["public"]["Tables"]["assessments"]["Row"];
export type CertificatesRow = Database["public"]["Tables"]["certificates"]["Row"];
export type CohortAnnouncementsRow = Database["public"]["Tables"]["cohort_announcements"]["Row"];
export type CohortWaitlistRow = Database["public"]["Tables"]["cohort_waitlist"]["Row"];
export type CohortsRow = Database["public"]["Tables"]["cohorts"]["Row"];
export type ContactMessagesRow = Database["public"]["Tables"]["contact_messages"]["Row"];
export type CoursesRow = Database["public"]["Tables"]["courses"]["Row"];
export type DonationsRow = Database["public"]["Tables"]["donations"]["Row"];
export type EnrolmentsRow = Database["public"]["Tables"]["enrolments"]["Row"];
export type EventsRow = Database["public"]["Tables"]["events"]["Row"];
export type HomepageRow = Database["public"]["Tables"]["homepage"]["Row"];
export type ImpactStatsRow = Database["public"]["Tables"]["impact_stats"]["Row"];
export type LearnersRow = Database["public"]["Tables"]["learners"]["Row"];
export type LessonMaterialsRow = Database["public"]["Tables"]["lesson_materials"]["Row"];
export type LessonProgressRow = Database["public"]["Tables"]["lesson_progress"]["Row"];
export type LessonsRow = Database["public"]["Tables"]["lessons"]["Row"];
export type LiveSessionsRow = Database["public"]["Tables"]["live_sessions"]["Row"];
export type MediaRow = Database["public"]["Tables"]["media"]["Row"];
export type ModulesRow = Database["public"]["Tables"]["modules"]["Row"];
export type NewsRow = Database["public"]["Tables"]["news"]["Row"];
export type NewsletterSignupsRow = Database["public"]["Tables"]["newsletter_signups"]["Row"];
export type PagesRow = Database["public"]["Tables"]["pages"]["Row"];
export type PartnersRow = Database["public"]["Tables"]["partners"]["Row"];
export type PaystackEventsRow = Database["public"]["Tables"]["paystack_events"]["Row"];
export type ProfilesRow = Database["public"]["Tables"]["profiles"]["Row"];
export type ProgrammesRow = Database["public"]["Tables"]["programmes"]["Row"];
export type QuizOptionsRow = Database["public"]["Tables"]["quiz_options"]["Row"];
export type QuizQuestionsRow = Database["public"]["Tables"]["quiz_questions"]["Row"];
export type RateLimitsRow = Database["public"]["Tables"]["rate_limits"]["Row"];
export type ReachCountriesRow = Database["public"]["Tables"]["reach_countries"]["Row"];
export type RegistrationsRow = Database["public"]["Tables"]["registrations"]["Row"];
export type ResourcesRow = Database["public"]["Tables"]["resources"]["Row"];
export type SessionAttendanceRow = Database["public"]["Tables"]["session_attendance"]["Row"];
export type SubmissionsRow = Database["public"]["Tables"]["submissions"]["Row"];
export type TeamMembersRow = Database["public"]["Tables"]["team_members"]["Row"];
export type TestimonialsRow = Database["public"]["Tables"]["testimonials"]["Row"];
export type ApplicationStatus = Database["public"]["Enums"]["application_status"];
export type AssessmentKind = Database["public"]["Enums"]["assessment_kind"];
export type ContactType = Database["public"]["Enums"]["contact_type"];
export type ContentStatus = Database["public"]["Enums"]["content_status"];
export type CurrencyCode = Database["public"]["Enums"]["currency_code"];
export type EnrolmentPaymentStatus = Database["public"]["Enums"]["enrolment_payment_status"];
export type EnrolmentState = Database["public"]["Enums"]["enrolment_state"];
export type EventType = Database["public"]["Enums"]["event_type"];
export type LocationType = Database["public"]["Enums"]["location_type"];
export type PaymentStatus = Database["public"]["Enums"]["payment_status"];
export type ResourceCategory = Database["public"]["Enums"]["resource_category"];
export type SubmissionState = Database["public"]["Enums"]["submission_state"];
export type TeamGroup = Database["public"]["Enums"]["team_group"];
