import "server-only";
import { createHmac, timingSafeEqual, randomUUID } from "node:crypto";

/* Paystack integration (Design.md §13). Server-side only — the secret key never
 * reaches the browser. Three responsibilities:
 *   1. initialize a transaction  → POST /transaction/initialize
 *   2. verify a transaction      → GET  /transaction/verify/:reference
 *   3. verify a webhook signature → HMAC-SHA512 of the RAW body (§13.4)
 *
 * The whole module is written to the live Paystack REST contract, so the moment
 * PAYSTACK_SECRET_KEY (+ public/webhook secrets) are set in .env, paid checkout
 * works with no further code changes. Until then, `isConfigured()` is false and
 * callers fall back to an honest "registration by enquiry" path — never a dead
 * or fake checkout. Amounts are always the minor unit (kobo/cents), integers. */

const BASE = "https://api.paystack.co";

const secretKey = process.env.PAYSTACK_SECRET_KEY;
const webhookSecret = process.env.PAYSTACK_WEBHOOK_SECRET || secretKey;

/** True once the secret key is present. Gate paid flows on this. */
export function isConfigured(): boolean {
  return Boolean(secretKey);
}

/** A collision-resistant, human-greppable transaction reference. */
export function newReference(prefix = "srn"): string {
  return `${prefix}_${Date.now()}_${randomUUID().slice(0, 8)}`;
}

type InitOk = {
  ok: true;
  authorizationUrl: string;
  accessCode: string;
  reference: string;
};
type InitErr = { ok: false; error: string };

/**
 * Initialize a transaction and get the hosted-checkout URL to redirect to.
 * `amount` is in the minor unit. `reference` is generated by the caller so the
 * registration row can store it before redirecting (§13.2).
 */
export async function initializeTransaction(opts: {
  email: string;
  amount: number;
  currency: "NGN" | "USD";
  reference: string;
  callbackUrl: string;
  metadata?: Record<string, unknown>;
}): Promise<InitOk | InitErr> {
  if (!secretKey) return { ok: false, error: "paystack-not-configured" };
  try {
    const res = await fetch(`${BASE}/transaction/initialize`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${secretKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        email: opts.email,
        amount: opts.amount,
        currency: opts.currency,
        reference: opts.reference,
        callback_url: opts.callbackUrl,
        metadata: opts.metadata,
      }),
    });
    const json = (await res.json()) as {
      status: boolean;
      message: string;
      data?: { authorization_url: string; access_code: string; reference: string };
    };
    if (!res.ok || !json.status || !json.data) {
      return { ok: false, error: json.message || `HTTP ${res.status}` };
    }
    return {
      ok: true,
      authorizationUrl: json.data.authorization_url,
      accessCode: json.data.access_code,
      reference: json.data.reference,
    };
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : "initialize failed",
    };
  }
}

export type VerifyResult =
  | {
      ok: true;
      status: string; // "success" | "failed" | "abandoned" | ...
      reference: string;
      amount: number;
      currency: string;
      paidAt: string | null;
    }
  | { ok: false; error: string };

/**
 * Server-side verification (§13.3): the authoritative confirmation of a charge,
 * used by the webhook and by the callback page as a belt-and-braces check.
 * Never trust the browser redirect alone.
 */
export async function verifyTransaction(
  reference: string,
): Promise<VerifyResult> {
  if (!secretKey) return { ok: false, error: "paystack-not-configured" };
  try {
    const res = await fetch(
      `${BASE}/transaction/verify/${encodeURIComponent(reference)}`,
      { headers: { Authorization: `Bearer ${secretKey}` } },
    );
    const json = (await res.json()) as {
      status: boolean;
      message: string;
      data?: {
        status: string;
        reference: string;
        amount: number;
        currency: string;
        paid_at: string | null;
      };
    };
    if (!res.ok || !json.status || !json.data) {
      return { ok: false, error: json.message || `HTTP ${res.status}` };
    }
    return {
      ok: true,
      status: json.data.status,
      reference: json.data.reference,
      amount: json.data.amount,
      currency: json.data.currency,
      paidAt: json.data.paid_at,
    };
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : "verify failed",
    };
  }
}

/**
 * §13.4 — verify the x-paystack-signature header: HMAC-SHA512 of the RAW,
 * unparsed body keyed with the secret, compared in constant time. The caller
 * MUST pass the raw request text (not a re-serialized object) or this will not
 * match. Returns false on any mismatch or missing config — fail closed.
 */
export function verifyWebhookSignature(
  rawBody: string,
  signature: string | null,
): boolean {
  if (!webhookSecret || !signature) return false;
  const expected = createHmac("sha512", webhookSecret)
    .update(rawBody, "utf8")
    .digest("hex");
  const a = Buffer.from(expected, "hex");
  const b = Buffer.from(signature, "hex");
  // Length guard first: timingSafeEqual throws on unequal lengths.
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}
