/* Phase 5.1 — preserve the recovered WordPress PDFs without making them
   public content. The source ZIP remains the immutable offline backup; this
   table is the controlled destination for certificates and other restricted
   learner records when they are uploaded by an administrator. */

create table if not exists private_documents (
  id uuid primary key default gen_random_uuid(),
  source_wp_id bigint,
  source_path text not null,
  file_name text not null,
  mime_type text not null default 'application/pdf',
  size_bytes bigint,
  source_sha256 text,
  classification text not null default 'certificate'
    check (classification in ('certificate', 'restricted_record', 'other')),
  storage_path text,
  matched_record_id text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'catalogued'
    check (status in ('catalogued', 'uploaded', 'matched', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists private_documents_source_unique
  on private_documents (source_path);
create index if not exists private_documents_classification_idx
  on private_documents (classification, status);

comment on table private_documents is
  'Phase 5.1. Catalogued WordPress certificates and restricted records. No public URL; bytes belong in the private wordpress-private-documents bucket and are served only through authenticated staff workflows.';

create table if not exists private_document_access_log (
  id bigint generated by default as identity primary key,
  document_id uuid not null references private_documents(id) on delete restrict,
  actor_id uuid,
  action text not null check (action in ('view', 'download', 'upload', 'match', 'archive')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists private_document_access_log_document_idx
  on private_document_access_log (document_id, created_at desc);

alter table private_documents enable row level security;
alter table private_document_access_log enable row level security;

drop policy if exists "staff manage private documents" on private_documents;
create policy "staff manage private documents" on private_documents
  for all to authenticated using (is_staff()) with check (is_staff());

drop policy if exists "staff read private document log" on private_document_access_log;
create policy "staff read private document log" on private_document_access_log
  for select to authenticated using (is_staff());

drop policy if exists "staff write private document log" on private_document_access_log;
create policy "staff write private document log" on private_document_access_log
  for insert to authenticated with check (is_staff());

drop trigger if exists private_documents_updated_at on private_documents;
create trigger private_documents_updated_at before update on private_documents
  for each row execute function set_updated_at();

insert into storage.buckets (id, name, public, file_size_limit)
values ('wordpress-private-documents', 'wordpress-private-documents', false, 52428800)
on conflict (id) do update set public = false;
